/* 
 * DocuSign Rooms API - v2
 *
 * An API for an integrator to access the features of DocuSign Rooms
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using DocuSign.Rooms.Client;
using DocuSign.Rooms.Model;

namespace DocuSign.Rooms.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFormProviderAssociationsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieves all Associations by provider
        /// </summary>
        /// <remarks>
        /// Retrieves all Associations for given provider
        /// </remarks>
        /// <exception cref="DocuSign.Rooms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">(Required) The globally unique identifier (GUID) for the account.</param>
        /// <param name="providerId">provider id like nar, nwmls etc..</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns></returns>
        FormProviderAssociationsSummaryList GetFormProviderAssociations(string accountId, string providerId, FormProviderAssociationsApi.GetFormProviderAssociationsOptions options = null);

        /// <summary>
        /// Retrieves all Associations by provider
        /// </summary>
        /// <remarks>
        /// Retrieves all Associations for given provider
        /// </remarks>
        /// <exception cref="DocuSign.Rooms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">(Required) The globally unique identifier (GUID) for the account.</param>
        /// <param name="providerId">provider id like nar, nwmls etc..</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>ApiResponse of </returns>
        ApiResponse<FormProviderAssociationsSummaryList> GetFormProviderAssociationsWithHttpInfo(string accountId, string providerId, FormProviderAssociationsApi.GetFormProviderAssociationsOptions options = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves all Associations by provider
        /// </summary>
        /// <remarks>
        /// Retrieves all Associations for given provider
        /// </remarks>
        /// <exception cref="DocuSign.Rooms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">(Required) The globally unique identifier (GUID) for the account.</param>
        /// <param name="providerId">provider id like nar, nwmls etc..</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of FormProviderAssociationsSummaryList</returns>
        System.Threading.Tasks.Task<FormProviderAssociationsSummaryList> GetFormProviderAssociationsAsync(string accountId, string providerId, FormProviderAssociationsApi.GetFormProviderAssociationsOptions options = null);

        /// <summary>
        /// Retrieves all Associations by provider
        /// </summary>
        /// <remarks>
        /// Retrieves all Associations for given provider
        /// </remarks>
        /// <exception cref="DocuSign.Rooms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">(Required) The globally unique identifier (GUID) for the account.</param>
        /// <param name="providerId">provider id like nar, nwmls etc..</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of ApiResponse (FormProviderAssociationsSummaryList)</returns>
        System.Threading.Tasks.Task<ApiResponse<FormProviderAssociationsSummaryList>> GetFormProviderAssociationsAsyncWithHttpInfo(string accountId, string providerId, FormProviderAssociationsApi.GetFormProviderAssociationsOptions options = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FormProviderAssociationsApi : IFormProviderAssociationsApi
    {
        private DocuSign.Rooms.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FormProviderAssociationsApi"/> class
        /// using AplClient object
        /// </summary>
        /// <param name="aplClient">An instance of AplClient</param>
        /// <returns></returns>
        public FormProviderAssociationsApi(DocuSignClient aplClient)
        {
            this.ApiClient = aplClient;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.ApiClient.GetBasePath();
        }

        /// <summary>
        /// Gets or sets the ApiClient object
        /// </summary>
        /// <value>An instance of the ApiClient</value>
        public DocuSignClient ApiClient { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public DocuSign.Rooms.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }


        /// <summary>
        /// Retrieves all Associations by provider Retrieves all Associations for given provider
        /// </summary>
        public class GetFormProviderAssociationsOptions
        {
            /// Total number of associations to be returned 
            public int? count {get; set;}
            /// starting position of the list 
            public int? startPosition {get; set;}
        }

        /// <summary>
        /// Retrieves all Associations by provider Retrieves all Associations for given provider
        /// </summary>
        /// <exception cref="DocuSign.Rooms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">(Required) The globally unique identifier (GUID) for the account.</param>
        /// <param name="providerId">provider id like nar, nwmls etc..</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>FormProviderAssociationsSummaryList</returns>
        public FormProviderAssociationsSummaryList GetFormProviderAssociations(string accountId, string providerId, FormProviderAssociationsApi.GetFormProviderAssociationsOptions options = null)
        {
             ApiResponse<FormProviderAssociationsSummaryList> localVarResponse = GetFormProviderAssociationsWithHttpInfo(accountId, providerId, options);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves all Associations by provider Retrieves all Associations for given provider
        /// </summary>
        /// <exception cref="DocuSign.Rooms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">(Required) The globally unique identifier (GUID) for the account.</param>
        /// <param name="providerId">provider id like nar, nwmls etc..</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>ApiResponse of FormProviderAssociationsSummaryList</returns>
        public ApiResponse<FormProviderAssociationsSummaryList> GetFormProviderAssociationsWithHttpInfo(string accountId, string providerId, FormProviderAssociationsApi.GetFormProviderAssociationsOptions options = null)
        {
            return GetFormProviderAssociationsAsyncWithHttpInfo(accountId, providerId, options)
                .ConfigureAwait(false)
                .GetAwaiter()
                .GetResult();
        }

        /// <summary>
        /// Retrieves all Associations by provider Retrieves all Associations for given provider
        /// </summary>
        /// <exception cref="DocuSign.Rooms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">(Required) The globally unique identifier (GUID) for the account.</param>
        /// <param name="providerId">provider id like nar, nwmls etc..</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of FormProviderAssociationsSummaryList</returns>
        public async System.Threading.Tasks.Task<FormProviderAssociationsSummaryList> GetFormProviderAssociationsAsync(string accountId, string providerId, FormProviderAssociationsApi.GetFormProviderAssociationsOptions options = null)
        {
             ApiResponse<FormProviderAssociationsSummaryList> localVarResponse = await GetFormProviderAssociationsAsyncWithHttpInfo(accountId, providerId, options);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves all Associations by provider Retrieves all Associations for given provider
        /// </summary>
        /// <exception cref="DocuSign.Rooms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">(Required) The globally unique identifier (GUID) for the account.</param>
        /// <param name="providerId">provider id like nar, nwmls etc..</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of ApiResponse (FormProviderAssociationsSummaryList)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<FormProviderAssociationsSummaryList>> GetFormProviderAssociationsAsyncWithHttpInfo(string accountId, string providerId, FormProviderAssociationsApi.GetFormProviderAssociationsOptions options = null)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling FormProviderAssociationsApi->GetFormProviderAssociations");
            // verify the required parameter 'providerId' is set
            if (providerId == null)
                throw new ApiException(400, "Missing required parameter 'providerId' when calling FormProviderAssociationsApi->GetFormProviderAssociations");

            var localVarPath = "/v2/accounts/{accountId}/form_providers/{providerId}/associations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", this.ApiClient.ParameterToString(accountId)); // path parameter
            if (providerId != null) localVarPathParams.Add("providerId", this.ApiClient.ParameterToString(providerId)); // path parameter
            if (options != null)
            {
                if (options.count != null) localVarQueryParams.Add("count", this.ApiClient.ParameterToString(options.count)); // query parameter
                if (options.startPosition != null) localVarQueryParams.Add("startPosition", this.ApiClient.ParameterToString(options.startPosition)); // query parameter
            }

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }

            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, HttpMethod.Get, localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = await this.ApiClient.CallApiAsync(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetFormProviderAssociations", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FormProviderAssociationsSummaryList>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (FormProviderAssociationsSummaryList)this.ApiClient.Deserialize(localVarResponse, typeof(FormProviderAssociationsSummaryList)));
        }

    }
}