/* 
 * DocuSign Rooms API - v2
 *
 * An API for an integrator to access the features of DocuSign Rooms
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = DocuSign.Rooms.Client.SwaggerDateConverter;

namespace DocuSign.Rooms.Model
{
    /// <summary>
    /// ClosingStatus
    /// </summary>
    [DataContract]
    public partial class ClosingStatus :  IEquatable<ClosingStatus>, IValidatableObject
    {
        public ClosingStatus()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClosingStatus" /> class.
        /// </summary>
        /// <param name="ClosingStatusId">ClosingStatusId.</param>
        /// <param name="Name">Name.</param>
        public ClosingStatus(string ClosingStatusId = default(string), string Name = default(string))
        {
            this.ClosingStatusId = ClosingStatusId;
            this.Name = Name;
        }
        
        /// <summary>
        /// Gets or Sets ClosingStatusId
        /// </summary>
        [DataMember(Name="closingStatusId", EmitDefaultValue=false)]
        public string ClosingStatusId { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClosingStatus {\n");
            sb.Append("  ClosingStatusId: ").Append(ClosingStatusId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ClosingStatus);
        }

        /// <summary>
        /// Returns true if ClosingStatus instances are equal
        /// </summary>
        /// <param name="other">Instance of ClosingStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClosingStatus other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ClosingStatusId == other.ClosingStatusId ||
                    this.ClosingStatusId != null &&
                    this.ClosingStatusId.Equals(other.ClosingStatusId)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ClosingStatusId != null)
                    hash = hash * 59 + this.ClosingStatusId.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
