/* 
 * DocuSign Rooms API - v2
 *
 * An API for an integrator to access the features of DocuSign Rooms
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Rooms.Model
{
    /// <summary>
    /// FormSummary
    /// </summary>
    [DataContract]
    public partial class FormSummary :  IEquatable<FormSummary>, IValidatableObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="FormSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public FormSummary()
        {
        }
        
        /// <summary>
        /// Gets or Sets LibraryFormId
        /// </summary>
        [DataMember(Name="libraryFormId", EmitDefaultValue=false)]
        public Guid? LibraryFormId { get; private set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; private set; }
        /// <summary>
        /// Gets or Sets LastUpdatedDate
        /// </summary>
        [DataMember(Name="lastUpdatedDate", EmitDefaultValue=false)]
        public DateTime? LastUpdatedDate { get; private set; }
        /// <summary>
        /// Gets or Sets ViewingUserHasAccess
        /// </summary>
        [DataMember(Name="viewingUserHasAccess", EmitDefaultValue=false)]
        public bool? ViewingUserHasAccess { get; private set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FormSummary {\n");
            sb.Append("  LibraryFormId: ").Append(LibraryFormId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  LastUpdatedDate: ").Append(LastUpdatedDate).Append("\n");
            sb.Append("  ViewingUserHasAccess: ").Append(ViewingUserHasAccess).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as FormSummary);
        }

        /// <summary>
        /// Returns true if FormSummary instances are equal
        /// </summary>
        /// <param name="other">Instance of FormSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FormSummary other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.LibraryFormId == other.LibraryFormId ||
                    this.LibraryFormId != null &&
                    this.LibraryFormId.Equals(other.LibraryFormId)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.LastUpdatedDate == other.LastUpdatedDate ||
                    this.LastUpdatedDate != null &&
                    this.LastUpdatedDate.Equals(other.LastUpdatedDate)
                ) && 
                (
                    this.ViewingUserHasAccess == other.ViewingUserHasAccess ||
                    this.ViewingUserHasAccess != null &&
                    this.ViewingUserHasAccess.Equals(other.ViewingUserHasAccess)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.LibraryFormId != null)
                    hash = hash * 59 + this.LibraryFormId.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.LastUpdatedDate != null)
                    hash = hash * 59 + this.LastUpdatedDate.GetHashCode();
                if (this.ViewingUserHasAccess != null)
                    hash = hash * 59 + this.ViewingUserHasAccess.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
