/* 
 * ProofService API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Rooms.Model
{
    /// <summary>
    /// Definition of the object that is used as a response of a managed token.
    /// </summary>
    [DataContract]
    public partial class GenerateProofFileLinkResponse :  IEquatable<GenerateProofFileLinkResponse>, IValidatableObject
    {
        public GenerateProofFileLinkResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateProofFileLinkResponse" /> class.
        /// </summary>
        /// <param name="SecretUri">Secret URI generated and containing the managed token..</param>
        public GenerateProofFileLinkResponse(string SecretUri = default(string))
        {
            this.SecretUri = SecretUri;
        }
        
        /// <summary>
        /// Secret URI generated and containing the managed token.
        /// </summary>
        /// <value>Secret URI generated and containing the managed token.</value>
        [DataMember(Name="secret_uri", EmitDefaultValue=false)]
        public string SecretUri { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GenerateProofFileLinkResponse {\n");
            sb.Append("  SecretUri: ").Append(SecretUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GenerateProofFileLinkResponse);
        }

        /// <summary>
        /// Returns true if GenerateProofFileLinkResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GenerateProofFileLinkResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GenerateProofFileLinkResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SecretUri == other.SecretUri ||
                    this.SecretUri != null &&
                    this.SecretUri.Equals(other.SecretUri)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SecretUri != null)
                    hash = hash * 59 + this.SecretUri.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
