/* 
 * DocuSign Rooms API - v2
 *
 * An API for an integrator to access the features of DocuSign Rooms
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = DocuSign.Rooms.Client.SwaggerDateConverter;

namespace DocuSign.Rooms.Model
{
    /// <summary>
    /// GlobalOriginsOfLeads
    /// </summary>
    [DataContract]
    public partial class GlobalOriginsOfLeads :  IEquatable<GlobalOriginsOfLeads>, IValidatableObject
    {
        public GlobalOriginsOfLeads()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GlobalOriginsOfLeads" /> class.
        /// </summary>
        /// <param name="OriginsOfLeads">OriginsOfLeads.</param>
        public GlobalOriginsOfLeads(List<OriginOfLead> OriginsOfLeads = default(List<OriginOfLead>))
        {
            this.OriginsOfLeads = OriginsOfLeads;
        }
        
        /// <summary>
        /// Gets or Sets OriginsOfLeads
        /// </summary>
        [DataMember(Name="originsOfLeads", EmitDefaultValue=false)]
        public List<OriginOfLead> OriginsOfLeads { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GlobalOriginsOfLeads {\n");
            sb.Append("  OriginsOfLeads: ").Append(OriginsOfLeads).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GlobalOriginsOfLeads);
        }

        /// <summary>
        /// Returns true if GlobalOriginsOfLeads instances are equal
        /// </summary>
        /// <param name="other">Instance of GlobalOriginsOfLeads to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GlobalOriginsOfLeads other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.OriginsOfLeads == other.OriginsOfLeads ||
                    this.OriginsOfLeads != null &&
                    this.OriginsOfLeads.SequenceEqual(other.OriginsOfLeads)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.OriginsOfLeads != null)
                    hash = hash * 59 + this.OriginsOfLeads.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
