/* 
 * DocuSign Rooms API - v2
 *
 * An API for an integrator to access the features of DocuSign Rooms
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Rooms.Model
{
    /// <summary>
    /// Defines ListingType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ListingType
    {
        
        /// <summary>
        /// Enum PublicRecords for value: PublicRecords
        /// </summary>
        [EnumMember(Value = "PublicRecords")]
        PublicRecords = 1,
        
        /// <summary>
        /// Enum MLS for value: MLS
        /// </summary>
        [EnumMember(Value = "MLS")]
        MLS = 2
    }

}
