/* 
 * DocuSign Rooms API - v2
 *
 * An API for an integrator to access the features of DocuSign Rooms
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = DocuSign.Rooms.Client.SwaggerDateConverter;

namespace DocuSign.Rooms.Model
{
    /// <summary>
    /// RegionReferenceCountList
    /// </summary>
    [DataContract]
    public partial class RegionReferenceCountList :  IEquatable<RegionReferenceCountList>, IValidatableObject
    {
        public RegionReferenceCountList()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RegionReferenceCountList" /> class.
        /// </summary>
        /// <param name="ReferenceCounts">ReferenceCounts.</param>
        public RegionReferenceCountList(List<RegionReferenceCount> ReferenceCounts = default(List<RegionReferenceCount>))
        {
            this.ReferenceCounts = ReferenceCounts;
        }
        
        /// <summary>
        /// Gets or Sets ReferenceCounts
        /// </summary>
        [DataMember(Name="referenceCounts", EmitDefaultValue=false)]
        public List<RegionReferenceCount> ReferenceCounts { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegionReferenceCountList {\n");
            sb.Append("  ReferenceCounts: ").Append(ReferenceCounts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as RegionReferenceCountList);
        }

        /// <summary>
        /// Returns true if RegionReferenceCountList instances are equal
        /// </summary>
        /// <param name="other">Instance of RegionReferenceCountList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegionReferenceCountList other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ReferenceCounts == other.ReferenceCounts ||
                    this.ReferenceCounts != null &&
                    this.ReferenceCounts.SequenceEqual(other.ReferenceCounts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ReferenceCounts != null)
                    hash = hash * 59 + this.ReferenceCounts.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
