/* 
 * DocuSign Rooms API - v2
 *
 * An API for an integrator to access the features of DocuSign Rooms
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Rooms.Model
{
    /// <summary>
    /// Defines RoomStatus
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RoomStatus
    {
        
        /// <summary>
        /// Enum Active for value: Active
        /// </summary>
        [EnumMember(Value = "Active")]
        Active = 1,
        
        /// <summary>
        /// Enum Pending for value: Pending
        /// </summary>
        [EnumMember(Value = "Pending")]
        Pending = 2,
        
        /// <summary>
        /// Enum Closed for value: Closed
        /// </summary>
        [EnumMember(Value = "Closed")]
        Closed = 3,
        
        /// <summary>
        /// Enum Open for value: Open
        /// </summary>
        [EnumMember(Value = "Open")]
        Open = 4
    }

}
